name: GhettoRecorder
services:
  GhettoRecorder:
    command: sleep infinity
    entrypoint: []
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONFAULTHANDLER: "1"
      PYTHONIOENCODING: "utf-8"
      PYTHONUNBUFFERED: "1"
      PYTHONUTF8: "1"
    hostname: GhettoRecorder
    image: alpine:3
    pull_policy: always
    volumes:
      - ..:/GhettoRecorder:cached
